-- Resources https://www.convertcsv.com/csv-to-sql.htm
-- Example: https://github.com/akuks/PerlForum/blob/master/Utilities/export_all.sql

-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET FOREIGN_KEY_CHECKS=0;


CREATE DATABASE IF NOT EXISTS airbnb;
USE airbnb;
--
-- Table 'lodgings'
--

DROP TABLE IF EXISTS `lodgings`;

CREATE TABLE `lodgings` (
   id           INTEGER  NOT NULL PRIMARY KEY
  ,city         VARCHAR(16) NOT NULL
  ,country      VARCHAR(13) NOT NULL
  ,description  VARCHAR(1477) NOT NULL
  ,name         VARCHAR(55) NOT NULL
  ,state        VARCHAR(12) NOT NULL
  ,state_abbrev VARCHAR(2) NOT NULL
  ,longitude    NUMERIC(11,7)
  ,latitude     NUMERIC(10,7)
  ,guests       INTEGER  NOT NULL
  ,bedrooms     INTEGER  NOT NULL
  ,beds         INTEGER  NOT NULL
  ,baths        INTEGER  NOT NULL
  ,price        INTEGER  NOT NULL
  ,host_id      INTEGER  NOT NULL
  ,rating       INTEGER  NOT NULL
  ,img_url      VARCHAR(90) NOT NULL
);

-- DROP TABLE IF EXISTS `lodgings`;

-- CREATE TABLE `lodgings` (
--   `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
--   `city` VARCHAR NULL DEFAULT NULL,
--   `country` VARCHAR NULL DEFAULT NULL,
--   `description` MEDIUMTEXT NULL DEFAULT NULL,
--   `name` VARCHAR NULL DEFAULT NULL,
--   `state` VARCHAR NULL DEFAULT NULL,
--   `state_abbrev` VARCHAR NULL DEFAULT NULL,
--   `longitude` DECIMAL NULL DEFAULT NULL,
--   `latitude` DECIMAL NULL DEFAULT NULL,
--   `guests` VARCHAR NULL DEFAULT NULL,
--   `bedrooms` INTEGER NULL DEFAULT NULL,
--   `beds` INTEGER NULL DEFAULT NULL,
--   `baths` DECIMAL NULL DEFAULT NULL,
--   `price` INTEGER NULL DEFAULT NULL,
--   `host_id` INTEGER NULL DEFAULT NULL,
--   `rating` DECIMAL NULL DEFAULT NULL,
--   `img_url` INTEGER NULL DEFAULT NULL,
--   PRIMARY KEY (`id`)

-- ---
-- Table 'hosts'
--
-- ---
DROP TABLE IF EXISTS `hosts`;

CREATE TABLE `hosts` (
   id        INTEGER  NOT NULL PRIMARY KEY
  ,name      VARCHAR(17) NOT NULL
  ,image_url VARCHAR(30)
  ,superhost BIT  NOT NULL
);

-- ---
-- Table 'reservations'
--
-- ---
DROP TABLE IF EXISTS `reservations`;

CREATE TABLE reservations(
   id       INTEGER  NOT NULL PRIMARY KEY
  ,lodge_id INTEGER  NOT NULL
  ,date_in  DATE  NOT NULL
  ,date_out DATE  NOT NULL
  ,guest_id INTEGER  NOT NULL
);


-- ---
-- Foreign Keys
-- ---

ALTER TABLE `lodgings` ADD FOREIGN KEY (host_id) REFERENCES `hosts` (`id`);
ALTER TABLE `reservations` ADD FOREIGN KEY (lodge_id) REFERENCES `lodgings` (`id`);



-- ---
-- Test Data
-- ---

INSERT INTO hosts(id,name,image_url,superhost) VALUES (1000,'Jeanette Oneal',NULL,1);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1001,'Owais Kenny',NULL,1);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1002,'Tahir Sanford',NULL,1);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1003,'Sarah-Jayne Berg',NULL,1);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1004,'Sally Blankenship',NULL,1);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1005,'Thalia Galloway',NULL,1);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1006,'Ayva Hudson',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1007,'Rudy Gibbs',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1008,'Maude O''Sullivan',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1009,'Faheem Hale',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1010,'Yasmeen Maguire',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1011,'Falak Velazquez',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1012,'Jackson Derrick',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1013,'Anthony Davey',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1014,'Mila Harmon',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1015,'Rhys Payne',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1016,'Serenity Davies',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1017,'Arlo Ramirez',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1018,'Aleyna Carver',NULL,0);
INSERT INTO hosts(id,name,image_url,superhost) VALUES (1019,'Asma Owen',NULL,0);



INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1000,'Ada','United States','Ada witch - Sometimes you can see a misty blue figure floating within a 3-mile radius of the Ada Cemetery on 2 Mile between Egypt Valley and Honey Creek. The story of her origin is as follows: A man suspected his wife of having an affair, so he followed her late one night when she thought he was asleep. Sure enough, she went to a field near their property where she met her lover. The husband was enraged and killed his wife, which resulted in a struggle with the other man. Both men died from their injuries. It is said that late at night (especially during the night of and the nights preceding a full moon) people driving by the field can see her ghost, searching for her lover. Some people have reported stopping to try to communicate with her, but she always disappears or runs into the woods where she cannot be followed (due to the thick brambles that inhabit the area). She is said to dress in a long white gown which authorities say dates her to the turn of the 20th century. Usually she is seen alone, but sometimes witnesses report seeing a ghostly death scene re-enacted... Others report seeing nothing at all but hearing the killer''s shouts of rage followed by the victims'' screams of agony... Although it is said she haunts the field on Honeycreek Road where she died, other witnesses have reported her in nearby Seidman Park, and in nearby Findlay Cemetery, where she is supposedly buried. This story was actually featured in the book "Ghosts of Grand Rapids."','Ada Cemetery','Michigan','MI',-85.5048931,42.9621061,5,4,5,2,453,1000,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1001,'Addison','United States','A little girl was killed suddenly while waiting for a school bus by a speeding car. Since her death things have happened. The day of her funeral she started knocking on doors of the house she was born in.1 month later as her clothes were to be removed the doors in the home flew open with no reason. Cold spots now can be felt & knocking at the door is still present to this day in the home. Also when there swings in the yard you could see them swing real high as if someone was swinging on them. lights like to go on & off in this home & she does move things to let someone know she is there. The cemetery where this child lies has had alot of activity also. When you visit her grave she has a twirly that will start going around & round with no reason or wind blowing to let you know she is present. Some have said she has been spotted walking the cemetery very restless as if she doesn''t realize she has passed on.','North Adams Rd.','Michigan','MI',-84.3818434,41.9714248,1,1,1,1,77,1001,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1002,'Allegan','United States','there have been notes of white dogs chasing cars that pull into the drive way. People have seen people hanging form trees and working in fields in old clothing. This motel is where Al Capone did some of his work and had meetings in a secret place in the tunnels. The motel was once painted blue but the next day it was back to yellow. - March 2007 update: was torn down and a tennis court was built over it.','The Yellow Motel','Michigan','MI',-85.8744224,42.5341643,10,2,10,2,184,1002,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1003,'Dearborn Heights','United States','The right wing of this school was closed off, supposedly because a young girl hanged herself in the hallway''s bathroom. People claim to hear sobbing and see drops of water drip from thin air.','O.W. Best Middle School','Michigan','MI',-83.2546347,42.2726796,9,1,9,1,120,1003,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1004,'Pittsburgh','United States','The Basement of "old Main" is said to be haunted by slaves, as it was a part of the Underground Railroad. Employees have been said to hear voices and moans. Lights go on and off and doors slam by themselves. Many unexplained happenings','"Old Main" Administration Building- Duquesne University','Pennsylvania','PA',-79.9901728,40.4372949,8,2,8,2,205,1004,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1005,'St. Charles','United States','The sounds of footsteps from an unoccupied floor can be heard.','St. Charles Nursing Home','Missouri','MO',-90.5239396,38.7582227,10,1,10,1,77,1005,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1006,'St. Charles','United States','This campus is haunted by the spirit of Mary Sibley, founder of the college. Students have seen her image and heard piano music, which Mrs. Sibley was so fond of. Also, the campus theatre and library is said to be haunted.','Lindenwood University','Missouri','MO',-90.503717,38.787519,1,2,1,2,118,1006,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1007,'St. Charles','United States','Sibley hall -  students on the top floor have reported to wake up in mid-air with their mattress below them. There is one hallway that no students are allowed to enter, because it is haunted. It has been boarded shut.','Lindenwood University','Missouri','MO',-90.503717,38.787519,8,5,8,3,503,1007,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1008,'Ste. Genevieve','United States','a lot of the places in the downtown area are claimed to be haunted by people who lived in all of the old houses. (Ste. Gen was the 1st settlement west of the Mississippi, so it is really old) the Valle house across from Valle School and the Catholic Church is claimed to be haunted by the 1st owners of the house and their dogs. There have been reported cold spots and sometimes in storms or late at night you can hear the dogs running up and down the halls of the house.','downtown Ste. Genevieve','Missouri','MO',-90.0475582,37.9786618,5,5,5,3,333,1008,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1009,'St. James','United States','The legend goes that if you go down Spook Hollow road that you will end up at a cemetery. If you go into the cemetery at night that no matter what time of year it is the weather is nice and cozy. The legend also says that there were a group of children that were going to the cemetery to perform some kind of sacrifice. Some of the children can be heard from some of the sacrifices that were done. There is also a little house on that road that people say house some of the adults that were involved.','Spook Hollow','Missouri','MO',-91.6109923,37.9551828,1,1,1,1,75,1009,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1010,'St. Joseph','United States','It is said that if you go to the third floor at night and try to walk down the 200 foot hallway, you will get books thrown at you...it is also said that if u walk down the hall and yell, lockers will start opening and you will here people on the intercom talking from the main office in the building...the school is built on top of an old indian burial, when u walk into the main entrance of the school building, and as soon as you enter the door, you are stepping on the leader of the Indian tribe leader. And about 10-15 years ago a secretary died and now and days when you walk into the office you can smell the perfume she wore, and the chair that she sat in will always be lowered and comforted how she had it when she was a secretary at the school. Also on the third floor when you walk down it and look into classrooms through the door you can see people sitting in a room doing homework, the people doing homework there is sum old students who died in a car crash.','Benton High School','Missouri','MO',-94.8546245,39.7146613,5,4,5,2,95,1010,5,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1011,'St. Joseph','United States','AnnexThe annex of the school is haunted by a mysterious ghost. One night a woman reported seeing it enter a room, only to turn on the television set and sat down to watch. People have also claimed to see a red glowing light floating down the halls.','Benton High School','Missouri','MO',-94.8546245,39.7146613,6,2,6,2,81,1011,2,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1012,'St. Joseph','United States','A couple ghost dwell here. One whom particularly likes the Auditorium. And another one who plays pranks and resides mostly on the bathrooms. A group of girls have reported (as has many other students and faculty members) that they will flood the bathrooms. Especially on the main, 2nd and 3rd floors. The Theater Arts Teacher and classes have affectionately named the ghost that haunts the Auditorium.','Central High School','Missouri','MO',-94.8290168,39.7650378,9,4,9,2,240,1012,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1013,'St. Joseph','United States','After the floral shop shut down they tried to sell it but no one wants to buy it do to its weird happenings. There is a very eerie feeling when you enter the building. Plus it kind of looks like a castle. People have heard a beautiful sound of piano playing from the upper floors, they hear foot steps, noises in the fire place.','The Old Park Floral Building','Missouri','MO',-94.800501,39.735482,4,3,4,2,101,1013,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1014,'St. Joseph','United States','It''s the house of the resident C.W. Farquhar. It has been known by many people that have stayed in the basement long enough. The doors will lock. The lights will turn a light red color. Screams of many young girls. And full figured ghosts seen laying on the ground screaming. In 1975 a man brought many young girls to the basement and slowly killed them.','The Death Cellar','Missouri','MO',NULL,NULL,6,5,6,3,337,1014,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1015,'Pittsburgh','United States','A nun that lived in the convent there many years ago had died and her ghost is said to walk the hall of the third floor of the main school building after school hours. Most of the people who have claimed to have seen her are ones who stay after for extracurricular activities. She has no face so she is known as the faceless nun. When she is seen, she is walking down the hall with her head bowed down and her hands folded as if she is praying. Every year, incoming freshmen within their first two weeks of classes are told the story of the faceless nun. Some don''t believe it, yet a lot of students, past and present, as well as teachers, have claimed to see her.','Our Lady of the Sacred Heart High School','Pennsylvania','PA',-80.1565514,40.5022047,1,3,1,2,84,1015,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1016,'St. Joseph','United States','Strange noises and sightening have been reported and the 3rd floor is said to be haunted by a man in dress pants. An old patient is said to be seen wandering the halls through out the building. The most haunted part of the building is the Basement where the Morgue is located. Strange things such as the motion detecter going off rapidly when no one is around, the sewing machine starting, cries of help, sounds of whimpering and crying, and a man''s shadow and muttering have been heard. Ten groups, (four groups of 1, two groups of 2, two groups of 3, a group of 4, and a group of half of a schooling college class), have reported hearing a woman''s voice whisper "Help Me." at seperate times. And six groups, (two groups of one, three groups of three, and one family tour), have reported a man running towards the elevator bellowing "Why are you here? Get out!".','Glore Psychiatric Museum','Missouri','MO',-94.8083941,39.7762831,2,4,2,2,302,1016,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1017,'St. Joseph','United States','at night some of the guards have said to see the door of the guard shack open and the sound of footsteps as if someone was coming in the guard shack, one guard said he was doing his rounds and saw someone walking outback by the back fence, sounds come from the basement when no one is in the building.','St. Joeseph''s Foods','Missouri','MO',-94.8753934,39.720025,3,4,3,2,301,1017,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1018,'St. Joseph','United States','are reported to be haunted. Doors open and close by themselves.','The St. Joseph School District offices','Missouri','MO',-94.8484641,39.7668099,3,1,3,1,70,1018,4,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1019,'St. Joseph','United States','The building is an old furrier, and you can sometimes see the old man who ran it back in the day.','The Social Parlor','Missouri','MO',-94.8526713,39.7659205,7,5,7,3,202,1019,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1020,'St. Louis','United States','This is the actual site of an exorcism, the event the movie is based on. The original building was torn down some years ago. The exorcism was performed on a young (perhaps 11) year old boy. After a vision of St. Michael the spirit was vanquished. The site is part of the parking lot now. It has a reoccurring crack in the pavement directly under the room the exorcism was held in. On a side note, the boy was transferred back and forth from Alexian Bros to White house estates (A catholic retreat)','Alexian Brothers Hospital Site','Missouri','MO',-90.2286233,38.5834635,6,3,6,2,82,1000,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1021,'St. Louis','United States','The old house is now used as a book house and a little girl known as Valerie lives there there''s a newspaper article and her favorite room is the poetry room though she stay in the basement a lot! It is said that she fell into the well years ago.','The Book House','Missouri','MO',-90.3189126,38.6127318,7,1,7,1,117,1001,5,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1022,'St. Louis','United States','Reports of seeing the ghost of Christopher covered in blood screaming and shouting.','Christopher Rd.','Missouri','MO',-90.307935,38.4300375,10,2,10,2,125,1002,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1023,'St. Louis','United States','Apartment Building - Reports of strange feelings of being watched cold spots, rancid smells that disappear as soon as the appeared, footsteps of children running & playing sounding like they where on the roof at 2 or 3 in the morning.','Delor St. &amp; Alaska Ave','Missouri','MO',-90.2712682,38.5825398,8,5,8,3,298,1003,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1024,'St. Louis','United States','Powell Symphony Hall - The Powell ghost (dubbed "George" by stagehands) makes noises, plays with the lights and elevator, and is sometimes seen as a man in a white suit and white hat. He is thought to be a former vaudevillian.','downtown','Missouri','MO',-90.1916501,38.6266074,1,3,1,2,292,1004,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1025,'St. Louis','United States','the Sheldon Concert Hall - The Sheldon is thought to be haunted by its architect, who died before the place was finished; he also plays with the lights, has been known to change the levels on sound equipment, and makes strange noises. Sometimes he plays with the lights even during performances.','downtown','Missouri','MO',-90.1916501,38.6266074,8,1,8,1,92,1005,2,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1026,'Pittsburgh','United States','The basement of the club is the original basement of an old farmhouse in which a man hung himself. The ghost was exorcised years ago, but there have still been sightings of the small man and many strange noises.','Rolling Hills Country Club','Pennsylvania','PA',-80.1019562,40.276962,2,5,2,3,357,1006,4,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1027,'St. Louis','United States','A housekeeper on the 5th floor reports: sightings of people walking down the hall but when you get close enough to touch they disappear. Others report hearing the elevator door ding, a presence, voices and footsteps walking towards them, when no one is there.','Drury Inn &amp; Suites 270 &amp;OLIVE','Missouri','MO',-94.477961,37.0503045,6,4,6,2,307,1007,2,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1028,'St. Louis','United States','ghost of a 10 year old girl is seen floating near a tree here.','Edgewood Children''s Center','Missouri','MO',-90.3636553,38.5993142,9,2,9,2,224,1008,2,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1029,'St. Louis','United States','One of the most haunted buildings in the city. Cold spots, electrical anomalies, feelings of being watched, a piano that plays a note in the night, vibration from the floors, feelings of sadness, tapping on shoulders, and many photographic anomalies, film and digital. - March 2008 update: This is a Bed and Breakfast anyone who wants to stay can reserve a room','Lemp Mansion','Missouri','MO',-90.215887,38.5931793,4,3,4,2,297,1009,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1030,'St. Louis','United States','Has been closed since the 1985. Reports of people in the non-boarded windows. Reports of screams nearby. Feelings of being watched.WARNING - No Trespassing - The building is being renovated into codos the name will be The Georgian Condominiums.','Old City Hospital','Missouri','MO',-90.2641782,38.6368763,10,2,10,2,228,1010,5,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1031,'St. Louis','United States','1 person got killed in a fire. He would be in a room and doors would closed, hear footsteps when he is the only one in there. Had radio on and turned off by it self. Desk fell over in the room while he was cleaning.','Our Lady Of Sorrows School','Missouri','MO',-90.28316,38.577459,1,2,1,2,105,1011,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1032,'St. Louis','United States','parking lot - This site was formerly the Gratiot Street Prison. Here is a bit of history on the place. The building had been McDowell''s College, a medical college owned and operated by Joseph Nash McDowell. It was confiscated by the Federal authorities in the spring of 1861. In December 1861 the building was converted into a prison and later renamed. Even early Federal records often call the place "McDowell''s College." It was right in the midst of some of the wealthiest homes in St. Louis. General Fremont''s headquarters in the Brant Mansion were only a block away. Right across the street was the home of the wealthy Harrison family. Attached to Gratiot on the north was the Christian Brothers Academy. Unlike other Civil War prisons, Gratiot was used to hold just about anyone and everyone. Along with Confederate prisoners of war were also held civilians ("citizens"), women, children, confiscated slaves ("contrabands"), spies, saboteurs, political prisoners, guerrillas and bushwhackers, and even Federal soldiers who had committed crimes or had misbehaved. Of Confederate soldiers held at Gratiot, the most likely ones came from battles and states in the Mississippi River region as far south as New Orleans. They were sent north for processing at Gratiot then moved on to Alton and other eastern prisons. Also soldiers fighting in Missouri and Arkansas would be sent to St. Louis. There is more information here: CivilWarStLouis.com','Ralston Purina','Missouri','MO',-90.1985526,38.6189179,8,1,8,1,81,1012,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1033,'St. Louis','United States','In the largest theatre a man died of a heart attack. The doors to this theatre will not stay open after 11 pm and an eerie presence can be felt inside.April 2008 Correction - This theatre was not on the site of the Old Ronnie''s Drive in.','Ronnie''s 20 Cine','Missouri','MO',-90.362463,38.527309,8,4,8,2,121,1013,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1034,'St. Louis','United States','A long time ago a girl name Rose was driving along when here car stalled out going up a hill. The car rolled back to the bottom of the hill. After trying to restart the car she got out to look under the hood. That was when she was grabbed by a man and murdered by her car. Now people say that if you go to where she was killed you should dust the trunk of your car with flour and place a rose on the trunk. Then when you drive up the hill and check the trunk there will be handprints on the trunk and the rose will be gone. They say that her ghost helps every car get up the hill.','Rose Hill','Missouri','MO',-90.3238096,38.4253046,6,5,6,3,186,1014,4,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1035,'St. Louis','United States','Rumors of the school being built on a cemetery, the forth floor is off limits, when they built it, they did so over a cemetery and only moved the headstones. Bones surface on the football field and a grave collapsed in the front lawn and they had to fill it in. - May 2008 Additional information: One of the football players practicing football and tripped over what turned out to be a coffin that was resurfacing. His father was also present when a femur bone was excavated and determined to be a human bone. Two of his cousins who attended this high school went to the 4th floor with some of their friends and reported actually being able to hear what sounded like people banging on the door as if trying to escape. There was a fire that killed everyone on the 4th floor, which is why it is blocked off. No one knows how the fire got started and -  (according to local legend****) the nearest 3 fire stations that could have been there and probably saved the lives of some of the people on that floor, could not get their station doors to open for the trucks to get out. A station about 5 miles away had to respond and by the time they got there, it was too late. - Talking to a local retired fireman, he hadn’t heard of this local legend, but did report of a fire that happened at Roosevelt when the school was having the floors stripped. 3 off-duty firemen lost their lives while helping with the fire.','Roosevelt High School','Missouri','MO',-90.2368527,38.6002121,8,2,8,2,130,1015,5,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1036,'St. Louis','United States','There are three known ghosts that haunt this famous theme park. The first one is the ghost of a little girl that has been seen around various areas of the park running around and laughing. The second spirit is a girl named Stella who haunts several of the parks theaters, giving off cold spots and speaking to people. The last ghost to haunt this park is known as The Pigman. He has been spotted on the back service roads late at night and some of the employees have claimed to hear the echoes of pigs squealing in the distance.','Six Flags Theme Park','Missouri','MO',-90.675216,38.5132186,7,5,7,3,311,1016,2,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1037,'Pittsburgh','United States','This place is said to be haunted by 2 ghosts. On of which is Sarah Heinz who is what this building is named after, staff members said to have heard footsteps and saw flickering lights...and every so often they would hear very fait voices during the night. The other ghost is f a boy who died while playing basket ball in the gym, he was up on the balcony above the gym and was looking over into the gym and he accidentally fell, members and staff claimed to still hear a basketball bouncing even though there is nobody in the gym.','Sarah Heinz House Boys and Girls Club','Pennsylvania','PA',-79.993256,40.454777,9,5,9,3,599,1017,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1038,'St. Louis','United States','Witnesses have reported something jumping on them and jumping on beds to fin a figure run straight through the door into the hallway .','St. Louis Job Corps','Missouri','MO',-90.2687073,38.69513,1,3,1,2,203,1018,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1039,'St. Louis','United States','Old residence hall  - locked up now, but there is no electricity to it, yet every night a light shines. Electricians have tried to find a power source, and never have. - May 2004 Update: A graduate from SLU reports to have no recollection or any unused residence halls or buildings on campus. The post may either be outdated or just not true.','St. Louis University','Missouri','MO',-90.2338232,38.6354598,1,2,1,2,162,1019,2,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1040,'St. Louis','United States','Children’s ward is haunted. A patient stayed there and has seen a few strange things. The pen container on the nurses desk will slide to the other side. Children’s bedroom doors will close on by there selves, slamming shut. Late at night there is crying of children and laughing in the play room.','St. Lukes Hospital','Missouri','MO',-90.5028413,38.6513821,3,5,3,3,362,1016,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1041,'St. Louis','United States','St. Louis - Seton Hall - During odd hours of the days, footsteps can be heard running down the hall on the third floor. Knocks on doors, and unlocking door sounds can be heard, all while no one is around. This used to be the location of a hospital and then a "nun home"(cant remember the word). There are tunnels that connect this building with other buildings on that side of campus, although they are blocked off. Some have also said they had problems with waking up in the air.','University of Missouri','Missouri','MO',-90.30828,38.7092401,8,1,8,1,125,1016,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1042,'St. Louis','United States','Lynstone park - foot steps through the leaves are heard. Feelings of being watched and reports of apparitions.','Sunset Hills','Missouri','MO',-90.407341,38.5389423,10,1,10,1,72,1016,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1043,'St. Louis','United States','Believed to be haunted by a little girl in the upper part of the theatre, who is playful and likes to play tricks on people during rehearsals. Another spirit of an old lady whom the little girl is said to be terrified of, is in the basement of the theatre.','Webster Groves Theatre Guild','Missouri','MO',-90.339764,38.599005,2,2,2,2,173,1016,4,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1044,'St. Louis','United States','Loretto-Hilton Theater - The Loretto-Hilton is haunted by a tech guy who died there; he once saved someone who had leaned too far over the edge of a catwalk: the man was falling, and then felt someone pull him back -- only no one else was there.','Webster University','Missouri','MO',-90.3437667,38.5892883,5,3,5,2,260,1016,4,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1045,'St. Louis','United States','St. Louis - Seton Hall - During odd hours of the days, footsteps can be heard running down the hall on the third floor. Knocks on doors, and unlocking door sounds can be heard, all while no one is around. This used to be the location of a hospital and then a convent. There are tunnels that connect this building with other buildings on that side of campus, although they are blocked off. Some have also said they had problems with waking up in the air.','University of Missouri','Missouri','MO',-90.30828,38.7092401,2,3,2,2,123,1019,3,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1046,'Stanberry','United States','babies crying, an old man appearing out of no where by the forest line coming towards you swinging a lantern, then disappearing. Sticks breaking in the woods constantly like someone is walking out in the woods.','Coopers cemetery','Missouri','MO',-94.5500323,40.1876088,7,1,7,1,89,1019,1,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1047,'Stone','United States','Middle School Gym - Late at night a basketball can be heard as if the person who used to play for the school team was still there. Many years ago he was killed when a group of buddies skipped school to run around. His funeral was held in the gym with his coffin located underneath the goal that the ghost plays his basketball.','Reeds Spring','Missouri','MO',-93.3779641,36.7497827,3,1,3,1,86,1019,4,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1048,'Pittsburgh','United States','Captain Shields haunts his former home.','Shields House','Pennsylvania','PA',NULL,NULL,2,5,2,3,309,1019,5,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');
INSERT INTO lodgings(id,city,country,description,name,state,state_abbrev,longitude,latitude,guests,bedrooms,beds,baths,price,host_id,rating,img_url) VALUES (1049,'Sullivan','United States','A long time a go a man owned this property, he hung people out in his feild the tale is if you park down by the gate.. turn off your car you can see people walking out in the field, a little boy lurks around the gate. and you can hear odd noises. It''s been known for your car not to start back up. It''s a very freaky place. People own the property now they have horses but if you go down there on a full moon you can''t see the horses anywhere... you can search the fields up and down and wont find any kind of sigh of a horse.','Gates of Hell','Missouri','MO',NULL,NULL,3,3,3,2,286,1019,0,'https://www.longisland.com/site_media/images/article/subarticle_image/Amityville_house.jpg');



INSERT INTO reservations(id,lodge_id,date_in,date_out,guest_id) VALUES (9991000,1000,'2021-01-20','2021-01-25',777);
